name: Update GitHub Activity

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "chore: Update GitHub activity feed"
          MAX_LINES: 5
